#index:
#    path: /
#    controller: App\Controller\DefaultController::index
email:
    path: /email
    controller: App\Controller\CompetitionController::sendEmail
print_competition:
    path: '/toPdf/{id}'
    controller: 'App\Controller\CompetitionController::printCompetition'
